//////////////////////////////////////////////////////////////////////
//                                                                  //
//                     Created by RoseKavalier:                     //
//                     rosekavalierhc@gmail.com                     //
//                       Created: 2019-12-18                        //
//                      Last edit: 2019-12-18                       //
//        ***You may use or distribute these files freely           //
//            so long as this notice remains present.***            //
//                                                                  //
//////////////////////////////////////////////////////////////////////

#ifndef _H4_CONSTANTS_HPP_
#define _H4_CONSTANTS_HPP_

#include "H4_Core.hpp"
#include "H4_Base.hpp"

namespace h4
{
	namespace NH4Creatures
	{
		enum class eCreatures
		{
			AIR_ELEMENTAL    = 0,
			ARCHANGEL        = 1,
			BALLISTA         = 2,
			BANDIT           = 3,
			BEHEMOTH         = 4,
			BEHOLDER         = 5,
			BLACK_DRAGON     = 6,
			BONE_DRAGON      = 7,
			CENTAUR          = 8,
			CERBERUS         = 9,
			CHAMPION         = 10,
			CROSSBOWMAN      = 11,
			CRUSADER         = 12,
			CYCLOPS          = 13,
			VENOM_SPAWN      = 14,
			ARCHDEVIL        = 15,
			DRAGON_GOLEM     = 16,
			DWARF            = 17,
			EARTH_ELEMENTAL  = 18,
			EFREET           = 19,
			ELF              = 20,
			FAERIE_DRAGON    = 21,
			FIRE_ELEMENTAL   = 22,
			GARGOYLE         = 23,
			GENIE            = 24,
			GHOST            = 25,
			BERSERKER        = 26,
			GOLD_GOLEM       = 27,
			GRIFFIN          = 28,
			HALFLING         = 29,
			HARPY            = 30,
			HYDRA            = 31,
			ICE_DEMON        = 32,
			IMP              = 33,
			LEPRECHAUN       = 34,
			MAGE             = 35,
			MANTIS           = 36,
			MEDUSA           = 37,
			MERMAID          = 38,
			MINOTAUR         = 39,
			MONK             = 40,
			MUMMY            = 41,
			NAGA             = 42,
			NIGHTMARE        = 43,
			NOMAD            = 44,
			OGRE_MAGE        = 45,
			ORC              = 46,
			PEASANT          = 47,
			PHOENIX          = 48,
			PIKEMAN          = 49,
			PIRATE           = 50,
			SATYR            = 51,
			SEA_MONSTER      = 52,
			SKELETON         = 53,
			SQUIRE           = 54,
			SPRITE           = 55,
			THUNDERBIRD      = 56,
			TITAN            = 57,
			TROGLODYTE       = 58,
			TROLL            = 59,
			UNICORN          = 60,
			VAMPIRE          = 61,
			WATER_ELEMENTAL  = 62,
			WHITE_TIGER      = 63,
			WOLF             = 64,
			ZOMBIE           = 65,
			WASPWORT         = 66,
			GOBLIN_KNIGHT    = 67,
			EVIL_SORCERESS   = 68,
			GARGANTUAN       = 69,
			DARK_CHAMPION    = 70,
			CATAPULT         = 71,
			FRENZIED_GNASHER = 72,
			MEGA_DRAGON      = 73,
		};

		enum class eCreatureAbilities
		{
			THREE_HEADED_ATTACK               = 0,
			AGING                             = 1,
			AREA_ATTACK                       = 2,
			BERSERKER                         = 3,
			BINDING                           = 4,
			IMMUNE_TO_VISUAL_ATTACK           = 5,
			BLINDING                          = 6,
			BLOCK                             = 7,
			BLOODLUST                         = 8,
			BREATH_ATTACK                     = 9,
			CHAOS_WARD                        = 10,
			CHARGING                          = 11,
			COLD_ATTACK                       = 12,
			COLD_RESISTENCE                   = 13,
			CURSE                             = 14,
			DEVOURING                         = 15,
			DEATH_WARD                        = 16,
			ELEMENTALS                        = 17,
			EXTRA_MELEE                       = 18,
			EXTRA_RANGED                      = 19,
			FIRE_ATTACK                       = 20,
			FIRE_RESISTENCE                   = 21,
			FIRE_SHIELD                       = 22,
			FIRST_STRIKE                      = 23,
			NEGATE_FIRST_STRIKE               = 24,
			FLYING                            = 25,
			FORTUNE                           = 26,
			FREEZING_ATTACK                   = 27,
			GIANT_SLAYER                      = 28,
			MULTIPLE_ATTACK                   = 29,
			HYPNOTIZE                         = 30,
			IGNORE_WARDS                      = 31,
			IGNORE_ZONES_OF_CONTROL           = 32,
			INSUBSTANTIAL                     = 33,
			LIFE_WARD                         = 34,
			LIGHTING_ATTACK                   = 35,
			LONG_RANGE                        = 36,
			LONG_WEAPON                       = 37,
			MAGIC_IMMUNITY                    = 38,
			MAGIC_MIRROR                      = 39,
			MAGIC_RESISTENCE                  = 40,
			MANA_LEECH                        = 41,
			MECHANICAL                        = 42,
			MELEE_GIANT_SLAYER                = 43,
			MIRTH                             = 44,
			NEGATE_MIND_IMMUNITY              = 45,
			NO_RETALIATION                    = 46,
			NORMAL_MELEE                      = 47,
			FEAR_PANIC                        = 48,
			POISON                            = 49,
			RANDOM_HARMFUL_SPELLS             = 50,
			RANGED                            = 51,
			RANGED_FIRST_STRIKE               = 52,
			RANGED_GIANT_SLAYER               = 53,
			RANGED_STUN                       = 54,
			REBIRTH                           = 55,
			REGENERATION                      = 56,
			RESURRECTION                      = 57,
			BONUSES_AT_SEA                    = 58,
			SHOOTS_TWICE                      = 59,
			SHORT_RANGE                       = 60,
			NO_OBSTACLE_PENALTY_SIEGE_MACHINE = 61,
			SKELETAL                          = 62,
			SPELL_VULNERABILITY               = 63,
			SPELLCASTER                       = 64,
			STEALTH                           = 65,
			STONE_GAZE                        = 66,
			STONE_SKIN                        = 67,
			STRENGTH                          = 68,
			STRIKE_AND_RETURN                 = 69,
			STRIKES_TWICE                     = 70,
			STUNNING                          = 71,
			SUMMONS_DEMONS                    = 72,
			TAXPAYER                          = 73,
			TELEPORT                          = 74,
			TERROR                            = 75,
			TOUGHNESS                         = 76,
			UNDEAD                            = 77,
			UNLIMITED_RETALIATIONS            = 78,
			UNLIMITED_SHOTS                   = 79,
			LINE_DRAINING                     = 80,
			WEAKNESS                          = 81,
			UNUSED_ABILITY                    = 82,
			GREEK_FIRE                        = 83,
			ARC_BREATH_ATTACK                 = 84,
			SIEGE_CAPABLE                     = 85,
		};
	}
}

#endif /* #define _H4_CONSTANTS_HPP_ */